backend:
  name: git-gateway
  branch: main
local_backend: true  # Para pruebas locales
media_folder: "img"
public_folder: "/img"
collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "index"
        label: "Home Page"
        file: "index.html"
        fields:
          - { name: "title", label: "Title", widget: "string" }
