backend:
  name: git-gateway
  branch: main
  repo: FotoYa/mi-web  # ¡Esto es clave! Asegúrate de que coincida con tu repositorio
  commit_messages:
    create: "Creación: {{collection}} «{{slug}}»"
    update: "Actualización: {{collection}} «{{slug}}»"

# Configuración de archivos multimedia
media_folder: "img"          # Carpeta donde se guardarán las imágenes
public_folder: "/img"       # Ruta pública para acceder a ellas

# Colecciones (contenido editable)
collections:
  - name: "pages"
    label: "Páginas"
    files:
      - name: "index"
        label: "Página de inicio"
        file: "index.html"   # Archivo que se editará
        fields:
          - { name: "title", label: "Título principal", widget: "string" }
          - { name: "content", label: "Contenido", widget: "markdown" }
