backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Creación: {{collection}} «{{slug}}»"
    update: "Actualización: {{collection}} «{{slug}}»"
    delete: "Borrado: {{collection}} «{{slug}}»"
    uploadMedia: "Subida de imagen: {{path}}"
    deleteMedia: "Borrado de imagen: {{path}}"

# Configuración de medios (imágenes)
media_folder: "static/img"  # Carpeta donde se guardarán las imágenes
public_folder: "/img"      # Ruta pública para acceder a ellas

# Colecciones (tus páginas editables)
collections:
  - name: "pages"
    label: "Páginas"
    files:
      - name: "index"
        label: "Página de inicio"
        file: "index.html"
        fields:
          - { name: "title", label: "Título", widget: "string" }
          - { name: "body", label: "Contenido", widget: "markdown" }
