backend:
  name: git-gateway
  branch: main
  repo: FotoYa/mi-web  # ¡Asegúrate que coincida con tu repositorio!
  commit_messages:
    create: "Creación: {{collection}} «{{slug}}»"
    update: "Actualización: {{collection}} «{{slug}}»"

# Configuración simplificada (sin carpetas vacías)
media_folder: "uploads"  # Carpeta que el CMS creará automáticamente
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Páginas"
    files:
      - name: "index"
        label: "Página de inicio"
        file: "index.html"
        fields:
          - { name: "title", label: "Título", widget: "string" }
          - { name: "body", label: "Contenido", widget: "markdown" }
