backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "img"  # Carpeta donde se guardarán las imágenes
public_folder: "/img"
collections:
  - name: "pagina_inicio"
    label: "Editar Inicio"
    files:
      - name: "inicio"
        label: "Contenido de Inicio"
        file: "_data/inicio.json"  # Archivo donde se guardarán los cambios
        fields:
          - { name: "titulo_principal", label: "Título Principal", widget: "string" }
          - { name: "subtitulo", label: "Subtítulo", widget: "text" }
          - { name: "imagen_hero", label: "Imagen Principal", widget: "image" }